---
all:
  children:
    api_gateway:
      children:
        api_gateway_outbound:
          hosts:
            af-api-gw-out-01:
            af-api-gw-out-02:
            af-api-gw-out-03:
        api_gateway_inbound:
          hosts:
            af-api-gw-in-01:
            af-api-gw-in-02:
            af-api-gw-in-03:
    application_services:
      hosts:
        af-app-dev-01:
        af-app-stg-01:
        af-app-prd-01:
        af-pwa-01:
        af-payment-dev-01:
        af-payment-stg-01:
        af-payment-prd-01:
        af-vehicle-01:
        af-services-01:
        af-api-common-01:
    cicd_services:
      hosts:
        af-gitlab-01:
        af-gitlab-runner-01:
        af-nexus-01:
        af-hub-01:
    exception_hosts:
      hosts:
        af-push-01:
        af-vehicle-01:
        af-sentry-01:
        af-gitlab-01:
        af-gitlab-runner-01:
