---
all:
  vars:
    ansible_user: ansible_ops
    ansible_port: 22
    ansible_become: true
    ansible_python_interpreter: auto_silent
    atlasforge_domain: atlasforge.example
    atlasforge_ntp_source: ntp01.atlasforge.example
    atlasforge_registry: registry.atlasforge.example
    atlasforge_git: git.atlasforge.example
    atlasforge_nexus: nexus.atlasforge.example
  children:

    rocky_managed:
      hosts:
        af-api-gw-out-01:
          ansible_host: 10.44.20.11
          service_name: api-gateway-outbound
          real_hostname: af-api-gw-out-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-api-gw-out-02:
          ansible_host: 10.44.20.12
          service_name: api-gateway-outbound
          real_hostname: af-api-gw-out-02.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-api-gw-out-03:
          ansible_host: 10.44.20.13
          service_name: api-gateway-outbound
          real_hostname: af-api-gw-out-03.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-api-gw-in-01:
          ansible_host: 10.44.20.21
          service_name: api-gateway-inbound
          real_hostname: af-api-gw-in-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-api-gw-in-02:
          ansible_host: 10.44.20.22
          service_name: api-gateway-inbound
          real_hostname: af-api-gw-in-02.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-api-gw-in-03:
          ansible_host: 10.44.20.23
          service_name: api-gateway-inbound
          real_hostname: af-api-gw-in-03.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-app-dev-01:
          ansible_host: 10.44.20.31
          service_name: application-dev
          real_hostname: af-app-dev-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-app-stg-01:
          ansible_host: 10.44.20.32
          service_name: application-staging
          real_hostname: af-app-stg-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-app-prd-01:
          ansible_host: 10.44.20.33
          service_name: application-production
          real_hostname: af-app-prd-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-gitlab-01:
          ansible_host: 10.44.30.11
          service_name: gitlab-server
          real_hostname: af-gitlab-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Platform
        af-gitlab-runner-01:
          ansible_host: 10.44.30.12
          service_name: gitlab-runner
          real_hostname: af-gitlab-runner-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Platform
        af-nexus-01:
          ansible_host: 10.44.30.13
          service_name: artifact-repository
          real_hostname: af-nexus-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Platform
        af-pwa-01:
          ansible_host: 10.44.20.41
          service_name: pwa-service
          real_hostname: af-pwa-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-payment-dev-01:
          ansible_host: 10.44.20.51
          service_name: payment-dev
          real_hostname: af-payment-dev-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-payment-stg-01:
          ansible_host: 10.44.20.52
          service_name: payment-staging
          real_hostname: af-payment-stg-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-payment-prd-01:
          ansible_host: 10.44.20.53
          service_name: payment-production
          real_hostname: af-payment-prd-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-services-01:
          ansible_host: 10.44.20.62
          service_name: shared-services
          real_hostname: af-services-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-hub-01:
          ansible_host: 10.44.30.31
          service_name: container-registry
          real_hostname: af-hub-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Platform
        af-api-common-01:
          ansible_host: 10.44.20.71
          service_name: api-common
          real_hostname: af-api-common-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application

    ubuntu_exception:
      hosts:
        af-push-01:
          ansible_host: 10.44.30.21
          service_name: push-service
          real_hostname: af-push-01.atlasforge.example
          managed_os: Ubuntu
          managed_os_version: '22.04'
          baseline_scope: Ubuntu Exception
        af-vehicle-01:
          ansible_host: 10.44.20.61
          service_name: vehicle-service
          real_hostname: af-vehicle-01.atlasforge.example
          managed_os: Ubuntu
          managed_os_version: '22.04'
          baseline_scope: Ubuntu Exception
        af-sentry-01:
          ansible_host: 10.44.40.11
          service_name: sentry-observability
          real_hostname: af-sentry-01.atlasforge.example
          managed_os: Ubuntu
          managed_os_version: '22.04'
          baseline_scope: Ubuntu Exception

    application_tier:
      hosts:
        af-api-gw-out-01:
          ansible_host: 10.44.20.11
          service_name: api-gateway-outbound
          real_hostname: af-api-gw-out-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-api-gw-out-02:
          ansible_host: 10.44.20.12
          service_name: api-gateway-outbound
          real_hostname: af-api-gw-out-02.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-api-gw-out-03:
          ansible_host: 10.44.20.13
          service_name: api-gateway-outbound
          real_hostname: af-api-gw-out-03.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-api-gw-in-01:
          ansible_host: 10.44.20.21
          service_name: api-gateway-inbound
          real_hostname: af-api-gw-in-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-api-gw-in-02:
          ansible_host: 10.44.20.22
          service_name: api-gateway-inbound
          real_hostname: af-api-gw-in-02.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-api-gw-in-03:
          ansible_host: 10.44.20.23
          service_name: api-gateway-inbound
          real_hostname: af-api-gw-in-03.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-app-dev-01:
          ansible_host: 10.44.20.31
          service_name: application-dev
          real_hostname: af-app-dev-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-app-stg-01:
          ansible_host: 10.44.20.32
          service_name: application-staging
          real_hostname: af-app-stg-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-app-prd-01:
          ansible_host: 10.44.20.33
          service_name: application-production
          real_hostname: af-app-prd-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-pwa-01:
          ansible_host: 10.44.20.41
          service_name: pwa-service
          real_hostname: af-pwa-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-payment-dev-01:
          ansible_host: 10.44.20.51
          service_name: payment-dev
          real_hostname: af-payment-dev-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-payment-stg-01:
          ansible_host: 10.44.20.52
          service_name: payment-staging
          real_hostname: af-payment-stg-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-payment-prd-01:
          ansible_host: 10.44.20.53
          service_name: payment-production
          real_hostname: af-payment-prd-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-services-01:
          ansible_host: 10.44.20.62
          service_name: shared-services
          real_hostname: af-services-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application
        af-api-common-01:
          ansible_host: 10.44.20.71
          service_name: api-common
          real_hostname: af-api-common-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Application

    platform_services:
      hosts:
        af-gitlab-01:
          ansible_host: 10.44.30.11
          service_name: gitlab-server
          real_hostname: af-gitlab-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Platform
        af-gitlab-runner-01:
          ansible_host: 10.44.30.12
          service_name: gitlab-runner
          real_hostname: af-gitlab-runner-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Platform
        af-nexus-01:
          ansible_host: 10.44.30.13
          service_name: artifact-repository
          real_hostname: af-nexus-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Platform
        af-hub-01:
          ansible_host: 10.44.30.31
          service_name: container-registry
          real_hostname: af-hub-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Platform

    observability_tier:
      hosts:
        af-sentry-01:
          ansible_host: 10.44.40.11
          service_name: sentry-observability
          real_hostname: af-sentry-01.atlasforge.example
          managed_os: Ubuntu
          managed_os_version: '22.04'
          baseline_scope: Ubuntu Exception

    firewalld_operational_exception:
      hosts:
        af-gitlab-01:
          ansible_host: 10.44.30.11
          service_name: gitlab-server
          real_hostname: af-gitlab-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Platform
        af-gitlab-runner-01:
          ansible_host: 10.44.30.12
          service_name: gitlab-runner
          real_hostname: af-gitlab-runner-01.atlasforge.example
          managed_os: Rocky Linux
          managed_os_version: '9.4'
          baseline_scope: Platform
