---
all:
  vars:
    ansible_user: ansible_ops
    ansible_port: 22
    ansible_become: true
    ansible_python_interpreter: auto_silent
    atlasforge_domain: atlasforge.example
    atlasforge_ntp_source: ntp01.atlasforge.example
    atlasforge_registry: registry.atlasforge.example
    atlasforge_git: git.atlasforge.example
    atlasforge_nexus: nexus.atlasforge.example
  children:
    api_gateway_tier:
      hosts:
        af-api-gw-in-01:
          ansible_host: 10.44.10.11
          service_ip: 10.44.20.11
          environment: lab-prd
          tier: 'API Gateway'
          service_name: api-gateway-inbound
          service_role: 'Inbound API Gateway Node 01'
          real_hostname: af-api-gw-in-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-api-gw-in-02:
          ansible_host: 10.44.10.12
          service_ip: 10.44.20.12
          environment: lab-prd
          tier: 'API Gateway'
          service_name: api-gateway-inbound
          service_role: 'Inbound API Gateway Node 02'
          real_hostname: af-api-gw-in-02.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-api-gw-out-01:
          ansible_host: 10.44.10.13
          service_ip: 10.44.20.13
          environment: lab-prd
          tier: 'API Gateway'
          service_name: api-gateway-outbound
          service_role: 'Outbound API Gateway Node 01'
          real_hostname: af-api-gw-out-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-api-gw-out-02:
          ansible_host: 10.44.10.14
          service_ip: 10.44.20.14
          environment: lab-prd
          tier: 'API Gateway'
          service_name: api-gateway-outbound
          service_role: 'Outbound API Gateway Node 02'
          real_hostname: af-api-gw-out-02.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
    web_tier:
      hosts:
        af-web-prd-01:
          ansible_host: 10.44.10.21
          service_ip: 10.44.20.21
          environment: lab-prd
          tier: 'Web Tier'
          service_name: web-frontend-prd
          service_role: 'Production Web Frontend 01'
          real_hostname: af-web-prd-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-web-prd-02:
          ansible_host: 10.44.10.22
          service_ip: 10.44.20.22
          environment: lab-prd
          tier: 'Web Tier'
          service_name: web-frontend-prd
          service_role: 'Production Web Frontend 02'
          real_hostname: af-web-prd-02.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-web-legacy-01:
          ansible_host: 10.44.10.23
          service_ip: 10.44.20.23
          environment: lab-prd
          tier: 'Web Tier'
          service_name: web-frontend-legacy
          service_role: 'Legacy Ubuntu Web Frontend Exception'
          real_hostname: af-web-legacy-01.atlasforge.example
          managed_os: 'Ubuntu'
          managed_os_version: '22.04'
          baseline_scope: 'Ubuntu Exception'
    application_api_tier:
      hosts:
        af-api-core-prd-01:
          ansible_host: 10.44.10.31
          service_ip: 10.44.20.31
          environment: lab-prd
          tier: 'Application API'
          service_name: core-api-prd
          service_role: 'Core API Service 01'
          real_hostname: af-api-core-prd-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-api-core-prd-02:
          ansible_host: 10.44.10.32
          service_ip: 10.44.20.32
          environment: lab-prd
          tier: 'Application API'
          service_name: core-api-prd
          service_role: 'Core API Service 02'
          real_hostname: af-api-core-prd-02.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-api-payment-prd-01:
          ansible_host: 10.44.10.33
          service_ip: 10.44.20.33
          environment: lab-prd
          tier: 'Application API'
          service_name: payment-api-prd
          service_role: 'Payment API Service'
          real_hostname: af-api-payment-prd-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-api-identity-prd-01:
          ansible_host: 10.44.10.34
          service_ip: 10.44.20.34
          environment: lab-prd
          tier: 'Application API'
          service_name: identity-api-prd
          service_role: 'Identity API Service'
          real_hostname: af-api-identity-prd-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-api-notification-legacy-01:
          ansible_host: 10.44.10.35
          service_ip: 10.44.20.35
          environment: lab-prd
          tier: 'Application API'
          service_name: notification-api-legacy
          service_role: 'Legacy Ubuntu Notification API Exception'
          real_hostname: af-api-notification-legacy-01.atlasforge.example
          managed_os: 'Ubuntu'
          managed_os_version: '22.04'
          baseline_scope: 'Ubuntu Exception'
    db_access_tier:
      hosts:
        af-db-proxy-01:
          ansible_host: 10.44.10.41
          service_ip: 10.44.20.41
          environment: lab-prd
          tier: 'DB Access'
          service_name: database-access-proxy
          service_role: 'Database Access Proxy 01'
          real_hostname: af-db-proxy-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-db-proxy-02:
          ansible_host: 10.44.10.42
          service_ip: 10.44.20.42
          environment: lab-prd
          tier: 'DB Access'
          service_name: database-access-proxy
          service_role: 'Database Access Proxy 02'
          real_hostname: af-db-proxy-02.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
    messaging_cache_tier:
      hosts:
        af-rmq-01:
          ansible_host: 10.44.10.51
          service_ip: 10.44.30.51
          environment: lab-prd
          tier: 'Messaging Cache'
          service_name: rabbitmq
          service_role: 'RabbitMQ Node 01'
          real_hostname: af-rmq-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-rmq-02:
          ansible_host: 10.44.10.52
          service_ip: 10.44.30.52
          environment: lab-prd
          tier: 'Messaging Cache'
          service_name: rabbitmq
          service_role: 'RabbitMQ Node 02'
          real_hostname: af-rmq-02.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-redis-01:
          ansible_host: 10.44.10.53
          service_ip: 10.44.30.53
          environment: lab-prd
          tier: 'Messaging Cache'
          service_name: redis-cache
          service_role: 'Redis Cache Node 01'
          real_hostname: af-redis-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
    devops_platform_tier:
      hosts:
        af-gitlab-01:
          ansible_host: 10.44.10.61
          service_ip: 10.44.30.61
          environment: lab-prd
          tier: 'DevOps Platform'
          service_name: gitlab
          service_role: 'GitLab SCM Platform'
          real_hostname: af-gitlab-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-gitlab-runner-01:
          ansible_host: 10.44.10.62
          service_ip: 10.44.30.62
          environment: lab-prd
          tier: 'DevOps Platform'
          service_name: gitlab-runner
          service_role: 'GitLab Runner Docker Executor'
          real_hostname: af-gitlab-runner-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-nexus-01:
          ansible_host: 10.44.10.63
          service_ip: 10.44.30.63
          environment: lab-prd
          tier: 'DevOps Platform'
          service_name: nexus
          service_role: 'Artifact Repository'
          real_hostname: af-nexus-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
    observability_tier:
      hosts:
        af-monitor-01:
          ansible_host: 10.44.10.71
          service_ip: 10.44.40.71
          environment: lab-prd
          tier: 'Observability'
          service_name: monitoring-stack
          service_role: 'Prometheus and Grafana'
          real_hostname: af-monitor-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-log-legacy-01:
          ansible_host: 10.44.10.72
          service_ip: 10.44.40.72
          environment: lab-prd
          tier: 'Observability'
          service_name: legacy-logging
          service_role: 'Legacy Ubuntu Logging Exception'
          real_hostname: af-log-legacy-01.atlasforge.example
          managed_os: 'Ubuntu'
          managed_os_version: '22.04'
          baseline_scope: 'Ubuntu Exception'
    rocky_managed:
      hosts:
        af-api-gw-in-01:
          ansible_host: 10.44.10.11
          service_ip: 10.44.20.11
          environment: lab-prd
          tier: 'API Gateway'
          service_name: api-gateway-inbound
          service_role: 'Inbound API Gateway Node 01'
          real_hostname: af-api-gw-in-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-api-gw-in-02:
          ansible_host: 10.44.10.12
          service_ip: 10.44.20.12
          environment: lab-prd
          tier: 'API Gateway'
          service_name: api-gateway-inbound
          service_role: 'Inbound API Gateway Node 02'
          real_hostname: af-api-gw-in-02.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-api-gw-out-01:
          ansible_host: 10.44.10.13
          service_ip: 10.44.20.13
          environment: lab-prd
          tier: 'API Gateway'
          service_name: api-gateway-outbound
          service_role: 'Outbound API Gateway Node 01'
          real_hostname: af-api-gw-out-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-api-gw-out-02:
          ansible_host: 10.44.10.14
          service_ip: 10.44.20.14
          environment: lab-prd
          tier: 'API Gateway'
          service_name: api-gateway-outbound
          service_role: 'Outbound API Gateway Node 02'
          real_hostname: af-api-gw-out-02.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-web-prd-01:
          ansible_host: 10.44.10.21
          service_ip: 10.44.20.21
          environment: lab-prd
          tier: 'Web Tier'
          service_name: web-frontend-prd
          service_role: 'Production Web Frontend 01'
          real_hostname: af-web-prd-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-web-prd-02:
          ansible_host: 10.44.10.22
          service_ip: 10.44.20.22
          environment: lab-prd
          tier: 'Web Tier'
          service_name: web-frontend-prd
          service_role: 'Production Web Frontend 02'
          real_hostname: af-web-prd-02.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-api-core-prd-01:
          ansible_host: 10.44.10.31
          service_ip: 10.44.20.31
          environment: lab-prd
          tier: 'Application API'
          service_name: core-api-prd
          service_role: 'Core API Service 01'
          real_hostname: af-api-core-prd-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-api-core-prd-02:
          ansible_host: 10.44.10.32
          service_ip: 10.44.20.32
          environment: lab-prd
          tier: 'Application API'
          service_name: core-api-prd
          service_role: 'Core API Service 02'
          real_hostname: af-api-core-prd-02.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-api-payment-prd-01:
          ansible_host: 10.44.10.33
          service_ip: 10.44.20.33
          environment: lab-prd
          tier: 'Application API'
          service_name: payment-api-prd
          service_role: 'Payment API Service'
          real_hostname: af-api-payment-prd-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-api-identity-prd-01:
          ansible_host: 10.44.10.34
          service_ip: 10.44.20.34
          environment: lab-prd
          tier: 'Application API'
          service_name: identity-api-prd
          service_role: 'Identity API Service'
          real_hostname: af-api-identity-prd-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-db-proxy-01:
          ansible_host: 10.44.10.41
          service_ip: 10.44.20.41
          environment: lab-prd
          tier: 'DB Access'
          service_name: database-access-proxy
          service_role: 'Database Access Proxy 01'
          real_hostname: af-db-proxy-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-db-proxy-02:
          ansible_host: 10.44.10.42
          service_ip: 10.44.20.42
          environment: lab-prd
          tier: 'DB Access'
          service_name: database-access-proxy
          service_role: 'Database Access Proxy 02'
          real_hostname: af-db-proxy-02.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-rmq-01:
          ansible_host: 10.44.10.51
          service_ip: 10.44.30.51
          environment: lab-prd
          tier: 'Messaging Cache'
          service_name: rabbitmq
          service_role: 'RabbitMQ Node 01'
          real_hostname: af-rmq-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-rmq-02:
          ansible_host: 10.44.10.52
          service_ip: 10.44.30.52
          environment: lab-prd
          tier: 'Messaging Cache'
          service_name: rabbitmq
          service_role: 'RabbitMQ Node 02'
          real_hostname: af-rmq-02.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-redis-01:
          ansible_host: 10.44.10.53
          service_ip: 10.44.30.53
          environment: lab-prd
          tier: 'Messaging Cache'
          service_name: redis-cache
          service_role: 'Redis Cache Node 01'
          real_hostname: af-redis-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-gitlab-01:
          ansible_host: 10.44.10.61
          service_ip: 10.44.30.61
          environment: lab-prd
          tier: 'DevOps Platform'
          service_name: gitlab
          service_role: 'GitLab SCM Platform'
          real_hostname: af-gitlab-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-gitlab-runner-01:
          ansible_host: 10.44.10.62
          service_ip: 10.44.30.62
          environment: lab-prd
          tier: 'DevOps Platform'
          service_name: gitlab-runner
          service_role: 'GitLab Runner Docker Executor'
          real_hostname: af-gitlab-runner-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-nexus-01:
          ansible_host: 10.44.10.63
          service_ip: 10.44.30.63
          environment: lab-prd
          tier: 'DevOps Platform'
          service_name: nexus
          service_role: 'Artifact Repository'
          real_hostname: af-nexus-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
        af-monitor-01:
          ansible_host: 10.44.10.71
          service_ip: 10.44.40.71
          environment: lab-prd
          tier: 'Observability'
          service_name: monitoring-stack
          service_role: 'Prometheus and Grafana'
          real_hostname: af-monitor-01.atlasforge.example
          managed_os: 'Rocky Linux'
          managed_os_version: '9.4'
          baseline_scope: 'Managed Rocky Linux'
    ubuntu_exception:
      hosts:
        af-web-legacy-01:
          ansible_host: 10.44.10.23
          service_ip: 10.44.20.23
          environment: lab-prd
          tier: 'Web Tier'
          service_name: web-frontend-legacy
          service_role: 'Legacy Ubuntu Web Frontend Exception'
          real_hostname: af-web-legacy-01.atlasforge.example
          managed_os: 'Ubuntu'
          managed_os_version: '22.04'
          baseline_scope: 'Ubuntu Exception'
        af-api-notification-legacy-01:
          ansible_host: 10.44.10.35
          service_ip: 10.44.20.35
          environment: lab-prd
          tier: 'Application API'
          service_name: notification-api-legacy
          service_role: 'Legacy Ubuntu Notification API Exception'
          real_hostname: af-api-notification-legacy-01.atlasforge.example
          managed_os: 'Ubuntu'
          managed_os_version: '22.04'
          baseline_scope: 'Ubuntu Exception'
        af-log-legacy-01:
          ansible_host: 10.44.10.72
          service_ip: 10.44.40.72
          environment: lab-prd
          tier: 'Observability'
          service_name: legacy-logging
          service_role: 'Legacy Ubuntu Logging Exception'
          real_hostname: af-log-legacy-01.atlasforge.example
          managed_os: 'Ubuntu'
          managed_os_version: '22.04'
          baseline_scope: 'Ubuntu Exception'
