---
project_name: ansible-managed-dc-baseline
project_version: v1.1.0
company_name: AtlasForge Bank
business_unit: Digital Infrastructure Engineering
environment_name: On-Prem / Air-Gapped Datacenter Lab
public_safe_dataset: true

atlasforge:
  domain: atlasforge.example
  registry: registry.atlasforge.example
  git: git.atlasforge.example
  nexus: nexus.atlasforge.example
  apt_mirror: apt-mirror.atlasforge.example
  ntp_source: ntp01.atlasforge.example
  management_cidr: 10.44.10.0/24
  application_cidr: 10.44.20.0/24
  platform_cidr: 10.44.30.0/24
  observability_cidr: 10.44.40.0/24

baseline_controls:
  required_hosts_entries:
    - { ip: "10.44.30.63", name: "nexus.atlasforge.example" }
    - { ip: "10.44.30.61", name: "git.atlasforge.example" }
    - { ip: "10.44.30.64", name: "registry.atlasforge.example" }
    - { ip: "10.44.10.10", name: "ntp01.atlasforge.example" }
  approved_repo_domains:
    - atlasforge.example
    - nexus.atlasforge.example
    - apt-mirror.atlasforge.example
    - registry.atlasforge.example
  expected_time_source: ntp01.atlasforge.example
  expected_docker_state: active
  expected_rocky_selinux_state: Enforcing
