---
- name: 67 Cis Preflight Basic Readonly Report
  hosts: baseline_readonly_scope
  gather_facts: true
  become: true
  serial: 1
  tasks:

    - name: Run CIS-like read-only preflight
      ansible.builtin.shell: |
        umask
findmnt /tmp || true
sysctl kernel.randomize_va_space || true
      args:
        executable: /bin/bash
      register: result_56579
      changed_when: false
      failed_when: false

